version: "3"
services:
  database:
    image: mongo
    ports:
      - 27017:27017
  app:
    build: .
    env_file: .env
    ports:
      - 4000:4004
    links:
      - database
    depends_on:
      - database
